// Built-in food database. kcal/protein/carbs/fat are per listed serving.
// unit: "x" = multiply by serving count
const FOOD_DB = [
  // Breakfast / eggs / dairy
  { id: "egg",        name: "Egg (boiled/fried)",      serving: "1 large (50 g)",   kcal: 78,  p: 6.3, c: 0.6, f: 5.3 },
  { id: "eggwhite",   name: "Egg white",               serving: "1 large",          kcal: 17,  p: 3.6, c: 0.2, f: 0.1 },
  { id: "oats",       name: "Oatmeal (dry oats)",      serving: "40 g",             kcal: 152, p: 5.3, c: 27,  f: 2.6 },
  { id: "granola",    name: "Granola",                 serving: "50 g",             kcal: 230, p: 5,   c: 32,  f: 9 },
  { id: "toastwhite", name: "White bread",             serving: "1 slice (25 g)",   kcal: 67,  p: 2.3, c: 12.6,f: 0.8 },
  { id: "toastwheat", name: "Whole wheat bread",       serving: "1 slice (28 g)",   kcal: 76,  p: 3.6, c: 12.9,f: 1.1 },
  { id: "butter",     name: "Butter",                  serving: "1 tsp (5 g)",      kcal: 36,  p: 0,   c: 0,   f: 4.1 },
  { id: "pbutter",    name: "Peanut butter",           serving: "1 tbsp (16 g)",    kcal: 96,  p: 4,   c: 3.5, f: 8.2 },
  { id: "jam",        name: "Jam",                     serving: "1 tbsp (20 g)",    kcal: 56,  p: 0.1, c: 13.8,f: 0 },
  { id: "milk",       name: "Milk, whole",             serving: "250 ml",           kcal: 152, p: 8,   c: 12,  f: 8 },
  { id: "milkskim",   name: "Milk, skim",              serving: "250 ml",           kcal: 86,  p: 8.4, c: 12.2,f: 0.4 },
  { id: "yogurt",     name: "Greek yogurt, plain",     serving: "170 g",            kcal: 100, p: 17,  c: 6,   f: 0.7 },
  { id: "yogurtfull", name: "Yogurt, full fat",        serving: "170 g",            kcal: 104, p: 5.9, c: 7.9, f: 5.5 },
  { id: "cheese",     name: "Cheddar cheese",          serving: "1 slice (28 g)",   kcal: 113, p: 6.4, c: 0.9, f: 9.3 },
  { id: "cottage",    name: "Cottage cheese",          serving: "100 g",            kcal: 98,  p: 11.1,c: 3.4, f: 4.3 },
  { id: "cereal",     name: "Breakfast cereal",        serving: "30 g + no milk",   kcal: 113, p: 2,   c: 25,  f: 0.8 },
  { id: "pancake",    name: "Pancake",                 serving: "1 medium (75 g)",  kcal: 175, p: 4.7, c: 22,  f: 7.4 },
  { id: "croissant",  name: "Croissant",               serving: "1 medium (57 g)",  kcal: 231, p: 4.7, c: 26,  f: 12 },

  // Protein mains
  { id: "chicken",    name: "Chicken breast, cooked",  serving: "100 g",            kcal: 165, p: 31,  c: 0,   f: 3.6 },
  { id: "chickenthigh",name:"Chicken thigh, cooked",   serving: "100 g",            kcal: 209, p: 26,  c: 0,   f: 10.9 },
  { id: "friedchicken",name:"Fried chicken",           serving: "1 piece (100 g)",  kcal: 246, p: 24,  c: 8,   f: 12.7 },
  { id: "beef",       name: "Beef, lean, cooked",      serving: "100 g",            kcal: 217, p: 26,  c: 0,   f: 11.8 },
  { id: "beefground", name: "Ground beef 80/20, cooked",serving:"100 g",            kcal: 254, p: 25.9,c: 0,   f: 15.9 },
  { id: "pork",       name: "Pork chop, cooked",       serving: "100 g",            kcal: 231, p: 25.7,c: 0,   f: 13.4 },
  { id: "bacon",      name: "Bacon",                   serving: "2 slices (16 g)",  kcal: 86,  p: 5.8, c: 0.2, f: 6.7 },
  { id: "salmon",     name: "Salmon, cooked",          serving: "100 g",            kcal: 208, p: 20,  c: 0,   f: 13 },
  { id: "tuna",       name: "Tuna, canned in water",   serving: "1 can (120 g)",    kcal: 128, p: 28,  c: 0,   f: 1 },
  { id: "whitefish",  name: "White fish, cooked",      serving: "100 g",            kcal: 105, p: 23,  c: 0,   f: 0.9 },
  { id: "shrimp",     name: "Shrimp, cooked",          serving: "100 g",            kcal: 99,  p: 24,  c: 0.2, f: 0.3 },
  { id: "tofu",       name: "Tofu, firm",              serving: "100 g",            kcal: 76,  p: 8,   c: 1.9, f: 4.8 },
  { id: "tempeh",     name: "Tempeh",                  serving: "100 g",            kcal: 192, p: 20.3,c: 7.6, f: 10.8 },
  { id: "protshake",  name: "Protein shake (1 scoop)", serving: "30 g powder",      kcal: 120, p: 24,  c: 3,   f: 1.5 },
  { id: "protbar",    name: "Protein bar",             serving: "1 bar (60 g)",     kcal: 220, p: 20,  c: 23,  f: 7 },
  { id: "sausage",    name: "Sausage",                 serving: "1 link (75 g)",    kcal: 230, p: 13,  c: 2,   f: 19 },
  { id: "ham",        name: "Ham, sliced",             serving: "2 slices (56 g)",  kcal: 61,  p: 9.3, c: 1.1, f: 2.2 },

  // Carbs / staples
  { id: "rice",       name: "White rice, cooked",      serving: "150 g (1 bowl)",   kcal: 195, p: 4,   c: 42,  f: 0.4 },
  { id: "ricebrown",  name: "Brown rice, cooked",      serving: "150 g (1 bowl)",   kcal: 165, p: 3.8, c: 34.5,f: 1.3 },
  { id: "friedrice",  name: "Fried rice",              serving: "1 plate (300 g)",  kcal: 500, p: 12,  c: 70,  f: 18 },
  { id: "pasta",      name: "Pasta, cooked",           serving: "180 g",            kcal: 284, p: 10.4,c: 55.5,f: 1.7 },
  { id: "noodlesinst",name: "Instant noodles",         serving: "1 pack (80 g dry)",kcal: 380, p: 8,   c: 52,  f: 15 },
  { id: "potato",     name: "Potato, boiled",          serving: "1 medium (170 g)", kcal: 147, p: 3.1, c: 34,  f: 0.2 },
  { id: "sweetpotato",name: "Sweet potato, baked",     serving: "1 medium (150 g)", kcal: 135, p: 3,   c: 31,  f: 0.2 },
  { id: "tortilla",   name: "Tortilla / wrap",         serving: "1 large (60 g)",   kcal: 180, p: 5,   c: 30,  f: 4.5 },
  { id: "bagel",      name: "Bagel",                   serving: "1 (95 g)",         kcal: 250, p: 10,  c: 49,  f: 1.5 },
  { id: "quinoa",     name: "Quinoa, cooked",          serving: "150 g",            kcal: 180, p: 6.6, c: 32,  f: 2.9 },
  { id: "corn",       name: "Corn, cooked",            serving: "1 ear (90 g)",     kcal: 88,  p: 3.3, c: 19,  f: 1.4 },

  // Veg & salad
  { id: "broccoli",   name: "Broccoli, cooked",        serving: "100 g",            kcal: 35,  p: 2.4, c: 7.2, f: 0.4 },
  { id: "spinach",    name: "Spinach, cooked",         serving: "100 g",            kcal: 23,  p: 3,   c: 3.8, f: 0.3 },
  { id: "saladgreen", name: "Green salad (no dressing)",serving:"1 bowl (100 g)",   kcal: 20,  p: 1.5, c: 3.5, f: 0.2 },
  { id: "caesar",     name: "Caesar salad w/ chicken", serving: "1 bowl (300 g)",   kcal: 390, p: 30,  c: 12,  f: 25 },
  { id: "carrot",     name: "Carrot",                  serving: "1 medium (60 g)",  kcal: 25,  p: 0.6, c: 5.8, f: 0.1 },
  { id: "cucumber",   name: "Cucumber",                serving: "100 g",            kcal: 15,  p: 0.7, c: 3.6, f: 0.1 },
  { id: "tomato",     name: "Tomato",                  serving: "1 medium (120 g)", kcal: 22,  p: 1.1, c: 4.8, f: 0.2 },
  { id: "avocado",    name: "Avocado",                 serving: "1/2 (70 g)",       kcal: 112, p: 1.4, c: 6,   f: 10.3 },
  { id: "mixveg",     name: "Mixed vegetables, cooked",serving: "150 g",            kcal: 60,  p: 3,   c: 12,  f: 0.5 },
  { id: "beans",      name: "Beans (kidney/black), cooked", serving: "130 g",       kcal: 165, p: 11,  c: 29,  f: 0.6 },
  { id: "lentils",    name: "Lentils, cooked",         serving: "150 g",            kcal: 174, p: 13.5,c: 30,  f: 0.6 },
  { id: "edamame",    name: "Edamame",                 serving: "100 g",            kcal: 121, p: 11.9,c: 8.9, f: 5.2 },

  // Fruit
  { id: "banana",     name: "Banana",                  serving: "1 medium (118 g)", kcal: 105, p: 1.3, c: 27,  f: 0.4 },
  { id: "apple",      name: "Apple",                   serving: "1 medium (180 g)", kcal: 95,  p: 0.5, c: 25,  f: 0.3 },
  { id: "orange",     name: "Orange",                  serving: "1 medium (130 g)", kcal: 62,  p: 1.2, c: 15.4,f: 0.2 },
  { id: "grapes",     name: "Grapes",                  serving: "100 g",            kcal: 69,  p: 0.7, c: 18,  f: 0.2 },
  { id: "strawberry", name: "Strawberries",            serving: "100 g",            kcal: 32,  p: 0.7, c: 7.7, f: 0.3 },
  { id: "blueberry",  name: "Blueberries",             serving: "100 g",            kcal: 57,  p: 0.7, c: 14.5,f: 0.3 },
  { id: "watermelon", name: "Watermelon",              serving: "200 g",            kcal: 60,  p: 1.2, c: 15.2,f: 0.3 },
  { id: "mango",      name: "Mango",                   serving: "1/2 (100 g)",      kcal: 60,  p: 0.8, c: 15,  f: 0.4 },
  { id: "pineapple",  name: "Pineapple",               serving: "100 g",            kcal: 50,  p: 0.5, c: 13,  f: 0.1 },
  { id: "kiwi",       name: "Kiwi",                    serving: "1 (75 g)",         kcal: 46,  p: 0.9, c: 11,  f: 0.4 },

  // Snacks & nuts
  { id: "almonds",    name: "Almonds",                 serving: "small handful (28 g)", kcal: 164, p: 6, c: 6.1, f: 14.2 },
  { id: "cashews",    name: "Cashews",                 serving: "small handful (28 g)", kcal: 157, p: 5.2, c: 8.6, f: 12.4 },
  { id: "peanuts",    name: "Peanuts",                 serving: "small handful (28 g)", kcal: 161, p: 7.3, c: 4.6, f: 14 },
  { id: "chips",      name: "Potato chips",            serving: "small bag (40 g)", kcal: 214, p: 2.8, c: 21,  f: 13.6 },
  { id: "popcorn",    name: "Popcorn, air-popped",     serving: "20 g",             kcal: 77,  p: 2.6, c: 15.6,f: 0.9 },
  { id: "chocolate",  name: "Chocolate",               serving: "4 squares (25 g)", kcal: 134, p: 1.9, c: 15,  f: 7.5 },
  { id: "cookie",     name: "Cookie",                  serving: "1 (30 g)",         kcal: 145, p: 1.7, c: 19,  f: 7 },
  { id: "icecream",   name: "Ice cream",               serving: "1 scoop (66 g)",   kcal: 137, p: 2.3, c: 15.6,f: 7.3 },
  { id: "donut",      name: "Donut, glazed",           serving: "1 (60 g)",         kcal: 240, p: 2.8, c: 27,  f: 13.7 },
  { id: "crackers",   name: "Crackers",                serving: "5 (15 g)",         kcal: 64,  p: 1.4, c: 11,  f: 1.6 },
  { id: "ricecake",   name: "Rice cake",               serving: "1 (9 g)",          kcal: 35,  p: 0.7, c: 7.3, f: 0.3 },
  { id: "darkchoc",   name: "Dark chocolate 85%",      serving: "2 squares (12 g)", kcal: 72,  p: 1.2, c: 4,   f: 5.7 },

  // Fast food / meals out
  { id: "pizza",      name: "Pizza",                   serving: "1 slice (107 g)",  kcal: 285, p: 12,  c: 36,  f: 10 },
  { id: "burger",     name: "Cheeseburger",            serving: "1 (150 g)",        kcal: 430, p: 22,  c: 35,  f: 22 },
  { id: "fries",      name: "French fries",            serving: "medium (115 g)",   kcal: 365, p: 4,   c: 48,  f: 17 },
  { id: "hotdog",     name: "Hot dog w/ bun",          serving: "1",                kcal: 290, p: 10,  c: 24,  f: 17 },
  { id: "burrito",    name: "Burrito (chicken)",       serving: "1 (300 g)",        kcal: 590, p: 32,  c: 70,  f: 19 },
  { id: "sandwich",   name: "Sandwich (deli)",         serving: "1 (220 g)",        kcal: 400, p: 20,  c: 45,  f: 15 },
  { id: "sushi",      name: "Sushi roll",              serving: "6 pieces",         kcal: 250, p: 9,   c: 38,  f: 6 },
  { id: "ramen",      name: "Ramen bowl",              serving: "1 bowl (550 g)",   kcal: 550, p: 22,  c: 75,  f: 18 },
  { id: "currychick", name: "Chicken curry w/ rice",   serving: "1 plate (400 g)",  kcal: 620, p: 28,  c: 78,  f: 21 },
  { id: "stirfry",    name: "Chicken stir-fry w/ rice",serving: "1 plate (400 g)",  kcal: 520, p: 30,  c: 62,  f: 15 },
  { id: "kebab",      name: "Kebab / shawarma wrap",   serving: "1 (350 g)",        kcal: 600, p: 30,  c: 55,  f: 28 },
  { id: "springroll", name: "Spring roll, fried",      serving: "1 (60 g)",         kcal: 130, p: 3,   c: 14,  f: 7 },
  { id: "dumpling",   name: "Dumplings, steamed",      serving: "4 (100 g)",        kcal: 165, p: 8,   c: 22,  f: 4.5 },
  { id: "soupveg",    name: "Vegetable soup",          serving: "1 bowl (300 ml)",  kcal: 100, p: 4,   c: 15,  f: 2.5 },
  { id: "soupchick",  name: "Chicken soup",            serving: "1 bowl (300 ml)",  kcal: 150, p: 12,  c: 12,  f: 5 },

  // Drinks
  { id: "coffee",     name: "Black coffee / tea",      serving: "1 cup",            kcal: 2,   p: 0.3, c: 0,   f: 0 },
  { id: "latte",      name: "Latte (whole milk)",      serving: "350 ml",           kcal: 190, p: 10,  c: 15,  f: 10 },
  { id: "cappuccino", name: "Cappuccino",              serving: "250 ml",           kcal: 90,  p: 5,   c: 8,   f: 4 },
  { id: "soda",       name: "Soda (cola)",             serving: "330 ml can",       kcal: 139, p: 0,   c: 39,  f: 0 },
  { id: "sodazero",   name: "Diet / zero soda",        serving: "330 ml can",       kcal: 1,   p: 0,   c: 0,   f: 0 },
  { id: "juiceor",    name: "Orange juice",            serving: "250 ml",           kcal: 112, p: 1.7, c: 26,  f: 0.5 },
  { id: "beer",       name: "Beer",                    serving: "330 ml",           kcal: 142, p: 1.5, c: 11,  f: 0 },
  { id: "wine",       name: "Wine",                    serving: "150 ml glass",     kcal: 123, p: 0.1, c: 4,   f: 0 },
  { id: "sportsdrink",name: "Sports drink",            serving: "500 ml",           kcal: 130, p: 0,   c: 34,  f: 0 },
  { id: "boba",       name: "Bubble tea (milk tea)",   serving: "500 ml",           kcal: 350, p: 2,   c: 65,  f: 8 },
  { id: "smoothie",   name: "Fruit smoothie",          serving: "350 ml",           kcal: 210, p: 3,   c: 48,  f: 1 },

  // Oils & condiments
  { id: "oliveoil",   name: "Olive oil",               serving: "1 tbsp (14 g)",    kcal: 119, p: 0,   c: 0,   f: 13.5 },
  { id: "cookingoil", name: "Cooking oil",             serving: "1 tbsp (14 g)",    kcal: 124, p: 0,   c: 0,   f: 14 },
  { id: "mayo",       name: "Mayonnaise",              serving: "1 tbsp (14 g)",    kcal: 94,  p: 0.1, c: 0.1, f: 10.3 },
  { id: "ketchup",    name: "Ketchup",                 serving: "1 tbsp (17 g)",    kcal: 17,  p: 0.2, c: 4.5, f: 0 },
  { id: "soysauce",   name: "Soy sauce",               serving: "1 tbsp (16 g)",    kcal: 8,   p: 1.3, c: 0.8, f: 0 },
  { id: "honey",      name: "Honey",                   serving: "1 tbsp (21 g)",    kcal: 64,  p: 0.1, c: 17.3,f: 0 },
  { id: "sugar",      name: "Sugar",                   serving: "1 tsp (4 g)",      kcal: 16,  p: 0,   c: 4,   f: 0 },
  { id: "dressing",   name: "Salad dressing",          serving: "1 tbsp (15 g)",    kcal: 60,  p: 0.1, c: 2.5, f: 5.5 },
  { id: "hummus",     name: "Hummus",                  serving: "2 tbsp (30 g)",    kcal: 70,  p: 2,   c: 4,   f: 5 }
];
